### ISSUE TITLE
Plus de PHP moins de JS

### ISSUE THREAD

**Issue by greut** [HE-Arc/Whatching#8]
Je viens vous embêter avec un gros changement car vous avez un problème de conception assez important.

![capture d ecran de 2016-11-28 10-14-54](https://cloud.githubusercontent.com/assets/1388/20662419/9cfff95a-b553-11e6-92d1-a5ec99322439.png)

Les deux barres (bleu et rouge) sont `DOMContentLoaded` et `load`. A priori tout doit être prêt à ce moment-là mais ça n'est pas le cas.

Que voit-on:
1. les deux barres violettes sont des appels à l'API de TMDb faites côté client :fearful:
2. deux petites barres vertes qui sont des appels à `addToDB` où vous tentez de populer la base données
3. deux images qui sont par chance dans le cache car elles font 780x1170 (300kB)

Cette page affiche deux films. Maintenant, admettons qu'elle en contienne 50. Donc 50 appels à l'API, 50 appels à votre addToDB, etc. C'est ceci qui ne va pas.

Voici des propositions d'améliorations que vous pouvez certainement séparer en trois.
- peupler votre base de données avec une série de films à l'aide d'un _seeder_. (Maximum 100 pour être raisonnable)
- permettre l'ajout d'un film (côté PHP)
- supprimer la barre de recherche pour vous concentrer sur la suggestion (ou vice-versa)

Au final, ce que vous allez gagner est:
- de ne pas publier votre clé privée à l'API de TMDb
- ~~d'avoir un contrôle sur la [taille des images](https://github.com/php-tmdb/laravel#image-helper), etc.~~
- de ne pas réinventer la roue: [php-tmdb/laravel](https://github.com/php-tmdb/laravel)

Bonne chance!

**Comment by drksnw** [comment]
JS 😭💔
